recipe: default.v1
language: en
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    model_name: gpt-3.5-turbo

policies:
- name: FlowPolicy
#- name: IntentlessPolicy
#- name: EnterpriseSearchPolicy
#- name: RulePolicy
assistant_id: 20240916-154228-lenient-key
